{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wall #-}

-- | C from "Core.Low". The second of D4's two stages, and deliberately the
-- dull one.
--
-- __This module contains no decisions.__ Every representational question —
-- what a record's struct is, what a constructor's tag is, what a closure
-- captures, where an allocation happens — was answered in "Core.Low", and what
-- arrives here is 'Rep' and 'TypeId'. @docs/m1a-c-spike.md@ §X6 makes that the
-- cheap test of D4's split: __the C printer may not read a 'Core.AST.Type'__,
-- and the way that is enforced is that this module does not import "Core.AST"
-- at all. If it ever needs to, the split has failed and @DESIGN.md@ §4.3a's
-- "add LLVM later" has become "write a second native backend".
--
-- The other thing to notice is @geng_alloc@. §X8 requires every allocation to
-- go through it from the first line, because that is what keeps D5's collector
-- a link-line decision rather than a rewrite. There are exactly three kinds of
-- allocation site below — a closure, a record and a constructor — each is
-- printed as its own typed maker function, and each maker calls @geng_alloc@.
module Generate.LowC
  ( generate,
    renderTags,
  )
where

import Core.Low
import Data.ByteString.Builder qualified as B
import Data.List qualified as List
import Data.Map (Map)
import Data.Map.Strict qualified as Map
import Data.Maybe qualified as Maybe
import Data.Name (Name)
import Data.Name qualified as Name
import Data.Set (Set)
import Data.Set qualified as Set
import Numeric qualified

-- | The whole C file.
generate :: Program -> B.Builder
generate prog =
  let needed = Set.unions (map (closuresIn . _funBody) (_lowFuns prog))
   in mconcat
        [ prologue prog,
          mconcat (map recordStruct (_lowRecords prog)),
          mconcat (map dataStruct (_lowDatas prog)),
          mconcat (map bounceStruct (_lowGroups prog)),
          mconcat (map envStruct (_lowFuns prog)),
          "/* forward declarations */\n",
          mconcat (map (declare prog) (_lowFuns prog)),
          mconcat [stepDeclare prog f | f <- _lowFuns prog, Maybe.isJust (_funGroup f)],
          mconcat [declareMaker f | f <- _lowFuns prog, Set.member (_funName f) needed],
          "\n/* allocation sites: every one of these calls geng_alloc (X8) */\n",
          mconcat (map recordAlloc (_lowRecords prog)),
          mconcat (map dataAlloc (_lowDatas prog)),
          mconcat [closureAlloc f | f <- _lowFuns prog, Set.member (_funName f) needed],
          mconcat (map (define prog) (_lowFuns prog)),
          entryPoint prog
        ]

-- | The @#define@s the hand-written C kernel is compiled against.
--
-- Written to @geng_tags.h@ beside the generated C. See 'Core.Low._lowBoolTags'
-- for why this exists at all: @core@ declares @True@ before @False@, so
-- @True@ is 0 and a kernel comparison returning C\'s @1@ returns @False@. The
-- tags are Core\'s, so they are emitted rather than agreed.
renderTags :: Program -> B.Builder
renderTags prog =
  "/* Generated by Generate.LowC beside the C. Core\'s own constructor tags,\n\
  \ * so that the hand-written kernel in geng_kernel.c is not written against a\n\
  \ * convention someone remembered. core declares True before False, so GENG_TRUE\n\
  \ * is 0 -- which is not what C\'s comparison operators return.\n\
  \ */\n\
  \#ifndef GENG_TAGS_H\n\
  \#define GENG_TAGS_H\n\n"
    <> ( case _lowBoolTags prog of
           Just (true, false) ->
             "#define GENG_TRUE "
               <> B.intDec true
               <> "\n"
               <> "#define GENG_FALSE "
               <> B.intDec false
               <> "\n"
           Nothing ->
             -- Bool is not reachable from this root, so nothing the generated C
             -- does can observe these. They are still emitted, because the
             -- hand-written kernel is one translation unit and declares its
             -- comparisons whether this program calls them or not.
             "/* Bool is not reachable from this root, so these are unused.\n\
             \ * They are emitted anyway: geng_kernel.c is compiled whole, and\n\
             \ * its comparisons name them whether this program calls them or not.\n\
             \ */\n\
             \#define GENG_TRUE 0\n\
             \#define GENG_FALSE 1\n"
       )
    <> "\n#endif\n"

-- | The functions some expression actually allocates a closure for.
--
-- A top-level function that is only ever called directly needs no maker, and
-- emitting one anyway is an unused-function warning in the generated C. The
-- set is a fold over "Core.Low"'s own nodes: 'XMakeClosure' is the single
-- construct that needs one.
closuresIn :: Expr -> Set String
closuresIn expr =
  case expr of
    XMakeClosure name args -> Set.insert name (Set.unions (map closuresIn args))
    XLet _ _ v rest -> Set.union (closuresIn v) (closuresIn rest)
    XIf c y n _ -> Set.unions [closuresIn c, closuresIn y, closuresIn n]
    XSwitch sc arms fb _ ->
      Set.unions (closuresIn sc : maybe Set.empty closuresIn fb : map (closuresIn . snd) arms)
    XCallTop _ args _ -> Set.unions (map closuresIn args)
    XCallKernel _ args _ -> Set.unions (map closuresIn args)
    XCallClosure f args _ -> Set.unions (closuresIn f : map closuresIn args)
    XMakeRecord _ args -> Set.unions (map closuresIn args)
    XMakeData _ _ args -> Set.unions (map closuresIn args)
    XField r _ _ -> closuresIn r
    XTagOf sc _ -> closuresIn sc
    XPayload sc _ _ _ _ -> closuresIn sc
    XJoin _ _ b rest -> Set.union (closuresIn b) (closuresIn rest)
    XJump _ args -> Set.unions (map closuresIn args)
    _ -> Set.empty

-- | The header comment, and §X5's budget written into the artifact.
--
-- The kernel list is not decoration. §X5 says the C kernel may implement only
-- names the linker reports as @missing@, and @harness/spike.py@ checks that on
-- every run — but the check reads the generated C, and a reader of the C should
-- not have to. Every name here stands behind a @missing@ entry in the spike's
-- own link report, which is written beside this file.
prologue :: Program -> B.Builder
prologue prog =
  "/* Generated by Generate.LowC. The Core -> C spike; docs/m1a-c-spike.md.\n\
  \ *\n\
  \ * Not a backend (X10): there is no `geng make --output=x.c`, no target in\n\
  \ * harness/run.py and no corpus. This file computes one value and prints it.\n\
  \ *\n\
  \ * The kernel functions this program needs (X5's budget, "
    <> B.intDec (length (_lowKernel prog))
    <> " of them):\n"
    <> mconcat [" *   " <> B.stringUtf8 n <> "\n" | n <- _lowKernel prog]
    <> " */\n\
       \#include \"geng_kernel.h\"\n\n"

-- TYPES

-- | A 'Rep' as a C type. The whole vocabulary the printer has.
ctype :: Rep -> B.Builder
ctype rep =
  case rep of
    RInt -> "int32_t"
    RFloat -> "double"
    RChar -> "int32_t"
    RString -> "geng_string *"
    RUnit -> "int32_t"
    REnum _ -> "int32_t"
    RData tid -> "struct " <> dataName tid <> " *"
    RRecord tid -> "struct " <> recordName tid <> " *"
    RClosure -> "geng_closure *"

recordName :: TypeId -> B.Builder
recordName (TypeId n) = "geng_r" <> B.intDec n

dataName :: TypeId -> B.Builder
dataName (TypeId n) = "geng_d" <> B.intDec n

-- | R2: "monomorphized struct, fields alphabetical". "Core.Low" interned the
-- layout; this prints it.
recordStruct :: RecordLayout -> B.Builder
recordStruct (RecordLayout tid fields) =
  "struct "
    <> recordName tid
    <> " {\n"
    <> ( if null fields
           then "    char geng_empty;\n"
           else mconcat ["    " <> ctype r <> " " <> field f <> ";\n" | (f, r) <- fields]
       )
    <> "};\n\n"

-- | A datatype. An all-nullary one is its tag and needs no struct at all,
-- which is the layout decision "Core.Low" made and the reason @if@ does not
-- allocate.
dataStruct :: DataLayout -> B.Builder
dataStruct layout
  | _dlEnum layout =
      "/* "
        <> B.stringUtf8 (_dlName layout)
        <> ": every constructor nullary, so the type is its tag */\n\n"
  | otherwise =
      "struct "
        <> dataName (_dlId layout)
        <> " {\n    int32_t tag;\n    union {\n"
        <> mconcat
          [ "        struct {\n"
              <> mconcat
                [ "            " <> ctype r <> " f" <> B.intDec i <> ";\n"
                | (i, r) <- zip [(0 :: Int) ..] (_clFields c)
                ]
              <> "        } c"
              <> B.intDec (_clTag c)
              <> ";\n"
          | c <- _dlCtors layout,
            not (null (_clFields c))
          ]
        <> "        char geng_empty;\n"
        <> "    } payload;\n};\n\n"

-- | D14's trampoline, as a struct.
--
-- One per mutually-recursive group. @next@ is the member to enter, or @-1@
-- when the group is done and @value@ holds the answer; @args@ is a union over
-- the members' parameter lists, because R2 gives native no uniform boxed
-- representation to pass them in. "Core.Low" computed the union; this prints
-- it.
bounceStruct :: Group -> B.Builder
bounceStruct g =
  "struct "
    <> B.stringUtf8 (_grName g)
    <> " {\n    int32_t next;\n    "
    <> ctype (_grResult g)
    <> " value;\n    union {\n"
    <> mconcat
      [ "        struct {\n"
          <> mconcat
            [ "            " <> ctype r <> " geng_a" <> B.intDec k <> ";\n"
            | (k, (_, r)) <- zip [(0 :: Int) ..] params
            ]
          <> (if null params then "            char geng_empty;\n" else "")
          <> "        } m"
          <> B.intDec i
          <> ";\n"
      | (i, (_, params)) <- zip [(0 :: Int) ..] (_grMembers g)
      ]
    <> "    } args;\n};\n\n"

groupOf :: Program -> Fun -> Maybe (Group, Int)
groupOf prog fun =
  do
    (name, i) <- _funGroup fun
    g <- Maybe.listToMaybe [g | g <- _lowGroups prog, _grName g == name]
    return (g, i)

-- | A group member's step function: the body, with a bounce instead of a tail
-- call to a sibling.
stepName :: Fun -> B.Builder
stepName fun = "geng_step_" <> B.stringUtf8 (_funName fun)

stepSignature :: Group -> Fun -> B.Builder
stepSignature g fun =
  "void "
    <> stepName fun
    <> "(struct "
    <> B.stringUtf8 (_grName g)
    <> " *geng_b, "
    <> commas
      ( "geng_closure *geng_self"
          : [ctype r <> " " <> local n | (n, r) <- _funParams fun]
      )
    <> ")"

stepDeclare :: Program -> Fun -> B.Builder
stepDeclare prog fun =
  case groupOf prog fun of
    Just (g, _) -> "static " <> stepSignature g fun <> ";\n"
    Nothing -> ""

-- | The captured environment of a closure, as a struct.
--
-- A struct rather than an untyped array because the capture set and every
-- capture's 'Rep' are known here — "Core.Low" computed them — so there is no
-- reason for the C to be less typed than the information allows.
envStruct :: Fun -> B.Builder
envStruct fun
  | null (_funCaptures fun) = ""
  | otherwise =
      "struct "
        <> envName fun
        <> " {\n"
        <> mconcat
          ["    " <> ctype r <> " " <> local n <> ";\n" | (n, r) <- _funCaptures fun]
        <> "};\n\n"

envName :: Fun -> B.Builder
envName fun = "geng_env_" <> B.stringUtf8 (_funName fun)

-- FUNCTIONS

-- | The calling convention, and it is one rule rather than two.
--
-- __Every function takes a leading @geng_closure *@__, whether it captures
-- anything or not, and a direct call passes @NULL@. The alternative — a
-- capture-free function with no environment parameter — means a top-level
-- function used as a value has a different C signature from the one an
-- indirect call site casts to, which is undefined behaviour that happens to
-- work until it does not. One uniform rule costs a null argument per direct
-- call and removes the whole question.
signature :: Fun -> B.Builder
signature fun =
  ctype (_funResult fun)
    <> " "
    <> B.stringUtf8 (_funName fun)
    <> "("
    <> commas
      ( "geng_closure *geng_self"
          : [ctype r <> " " <> local n | (n, r) <- _funParams fun]
      )
    <> ")"

-- | The function pointer type an indirect call casts through.
fnPointer :: Rep -> [Rep] -> B.Builder
fnPointer result args =
  ctype result <> " (*)(" <> commas ("geng_closure *" : map ctype args) <> ")"

declare :: Program -> Fun -> B.Builder
declare prog fun
  | Just (g, _) <- groupOf prog fun =
      -- Only where an entry is actually emitted; see 'needsEntry'.
      if needsEntry prog g fun then "static " <> signature fun <> ";\n" else ""
  | _funIsCaf fun =
      "static " <> ctype (_funResult fun) <> " " <> B.stringUtf8 (_funName fun) <> "(void);\n"
  | otherwise = "static " <> signature fun <> ";\n"

declareMaker :: Fun -> B.Builder
declareMaker fun
  | _funIsCaf fun = ""
  | otherwise = "static geng_closure *" <> makerName fun <> "(" <> makerParams fun <> ");\n"

makerName :: Fun -> B.Builder
makerName fun = "geng_mk_" <> B.stringUtf8 (_funName fun)

makerParams :: Fun -> B.Builder
makerParams fun =
  case [ctype r <> " " <> local n | (n, r) <- _funCaptures fun] of
    [] -> "void"
    ps -> commas ps

-- | Allocating a closure: the code pointer and the captured environment, in
-- one @geng_alloc@.
--
-- A typed maker per function rather than a variadic helper, because the
-- captures have different 'Rep's and a variadic call would throw exactly the
-- type information "Core.Low" worked to compute.
closureAlloc :: Fun -> B.Builder
closureAlloc fun
  | _funIsCaf fun = ""
  | otherwise =
      "static geng_closure *"
        <> makerName fun
        <> "("
        <> makerParams fun
        <> ") {\n    geng_closure *geng_it = geng_alloc(sizeof *geng_it + "
        <> ( if null (_funCaptures fun)
               then "0"
               else "sizeof(struct " <> envName fun <> ")"
           )
        <> ");\n    geng_it->code = (void *) "
        <> B.stringUtf8 (_funName fun)
        <> ";\n"
        <> ( if null (_funCaptures fun)
               then ""
               else
                 "    struct "
                   <> envName fun
                   <> " *geng_e = (struct "
                   <> envName fun
                   <> " *) geng_it->env;\n"
                   <> mconcat
                     [ "    geng_e->" <> local n <> " = " <> local n <> ";\n"
                     | (n, _) <- _funCaptures fun
                     ]
           )
        <> "    return geng_it;\n}\n\n"

-- | A function body, or a CAF's memoising accessor.
--
-- __A CAF is computed once into a static slot.__ That is sound here for the
-- reason §X8 gives: a spike program computes one value and exits, and the bump
-- allocator never frees, so nothing the CAF holds can go away underneath it.
define :: Program -> Fun -> B.Builder
define prog fun
  | Just (g, i) <- groupOf prog fun = trampoline prog g i fun
  | _funIsCaf fun =
      let n = B.stringUtf8 (_funName fun)
       in "static int geng_done_"
            <> n
            <> " = 0;\n"
            <> "static "
            <> ctype (_funResult fun)
            <> " geng_slot_"
            <> n
            <> ";\n"
            <> "static "
            <> ctype (_funResult fun)
            <> " "
            <> n
            <> "(void) {\n    if (!geng_done_"
            <> n
            <> ") {\n"
            <> body prog (Slot ("geng_slot_" <> n)) fun
            <> "        geng_done_"
            <> n
            <> " = 1;\n    }\n    return geng_slot_"
            <> n
            <> ";\n}\n\n"
  | otherwise =
      "static "
        <> signature fun
        <> " {\n    (void) geng_self;\n"
        <> unpackCaptures fun
        <> body prog Return fun
        -- Unreachable: every path through the body returns. It is here so that
        -- a body ending in a join point's end label -- which is a label with
        -- nothing after it -- is still a statement, and so that the compiler
        -- does not report control reaching the end of a non-void function.
        <> "    geng_crash(\"fell out of a function\");\n}\n\n"

body :: Program -> Dest -> Fun -> B.Builder
body prog dest fun =
  emit (Ctx (joinsIn (_funBody fun)) (bounceTargets prog)) [] dest (_funBody fun)

-- | Which member index each group member has, and under which bounce struct.
bounceTargets :: Program -> Map String Int
bounceTargets prog =
  Map.fromList
    [ (name, i)
    | g <- _lowGroups prog,
      (i, (name, _)) <- zip [0 ..] (_grMembers g)
    ]

-- | D14's trampoline: the step function, and the loop that drives it.
--
-- The member does not call its sibling; it writes the sibling's index and
-- arguments into the bounce and returns. The entry function loops until a
-- member says it is done. Every member of the group gets its own entry, so a
-- call from outside the group enters the loop wherever it meant to.
--
-- The stack cost is one frame for the loop and one for the step, whatever the
-- depth. That is the whole of D14, and `mutual-recursion` at ten million is
-- what says it was built: without it the same program is a SIGSEGV.
trampoline :: Program -> Group -> Int -> Fun -> B.Builder
trampoline prog g i fun =
  step <> (if needsEntry prog g fun then entry else "")
  where
    step =
      "static "
        <> stepSignature g fun
        <> " {\n    (void) geng_self;\n"
        <> unpackCaptures fun
        <> emit (Ctx (joinsIn (_funBody fun)) (bounceTargets prog)) [] Bounce (_funBody fun)
        <> "    geng_crash(\"fell out of a trampoline step\");\n}\n\n"
    entry =
      "static "
        <> signature fun
        <> " {\n    struct "
        <> B.stringUtf8 (_grName g)
        -- Zero-initialised so that `value` is not read before a step writes
        -- it. No step can be entered without writing it -- `next` only leaves
        -- the loop when one has -- but the compiler cannot see that, and a
        -- warning in the generated C is a finding here rather than noise.
        <> " geng_b = {0};\n    geng_b.next = "
        <> B.intDec i
        <> ";\n"
        <> mconcat
          [ "    geng_b.args.m"
              <> B.intDec i
              <> ".geng_a"
              <> B.intDec k
              <> " = "
              <> local n
              <> ";\n"
          | (k, (n, _)) <- zip [(0 :: Int) ..] (_funParams fun)
          ]
        <> "    for (;;) {\n        switch (geng_b.next) {\n"
        <> mconcat
          [ "        case "
              <> B.intDec j
              <> ":\n            geng_step_"
              <> B.stringUtf8 member
              <> "(&geng_b, geng_self"
              <> mconcat
                [ ", geng_b.args.m" <> B.intDec j <> ".geng_a" <> B.intDec k
                | (k, _) <- zip [(0 :: Int) ..] params
                ]
              <> ");\n            break;\n"
          | (j, (member, params)) <- zip [(0 :: Int) ..] (_grMembers g)
          ]
        <> "        default:\n            return geng_b.value;\n        }\n    }\n}\n\n"

-- | Does anything outside the group enter this member?
--
-- Every member could have an entry, and one per member is the general shape --
-- a call from outside enters the loop wherever it meant to. But a member
-- nothing outside calls would be an unused function, and the spike treats a
-- warning in the generated C as a finding. @isOdd@ is the case: the program
-- calls @isEven@ and only @isEven@ calls @isOdd@, from inside the trampoline.
needsEntry :: Program -> Group -> Fun -> Bool
needsEntry prog g fun =
  _funName fun == fst (_lowRoot prog) || Set.member (_funName fun) outside
  where
    mine = Set.fromList (map fst (_grMembers g))
    outside =
      Set.unions
        [ referencesIn (_funBody f)
        | f <- _lowFuns prog,
          not (Set.member (_funName f) mine)
        ]

-- | The top-level names a body calls or closes over.
referencesIn :: Expr -> Set String
referencesIn expr =
  case expr of
    XCallTop name args _ -> Set.insert name (Set.unions (map referencesIn args))
    XCaf name _ -> Set.singleton name
    XMakeClosure name args -> Set.insert name (Set.unions (map referencesIn args))
    XLet _ _ v rest -> Set.union (referencesIn v) (referencesIn rest)
    XIf c y n _ -> Set.unions [referencesIn c, referencesIn y, referencesIn n]
    XSwitch sc arms fb _ ->
      Set.unions (referencesIn sc : maybe Set.empty referencesIn fb : map (referencesIn . snd) arms)
    XCallKernel _ args _ -> Set.unions (map referencesIn args)
    XCallClosure f args _ -> Set.unions (referencesIn f : map referencesIn args)
    XMakeRecord _ args -> Set.unions (map referencesIn args)
    XMakeData _ _ args -> Set.unions (map referencesIn args)
    XField r _ _ -> referencesIn r
    XTagOf sc _ -> referencesIn sc
    XPayload sc _ _ _ _ -> referencesIn sc
    XJoin _ _ b rest -> Set.union (referencesIn b) (referencesIn rest)
    XJump _ args -> Set.unions (map referencesIn args)
    XBounce _ args -> Set.unions (map referencesIn args)
    _ -> Set.empty

-- | Bring the environment into scope, so the body prints a capture the same
-- way whatever function it is in.
unpackCaptures :: Fun -> B.Builder
unpackCaptures fun
  | null (_funCaptures fun) = ""
  | otherwise =
      "    struct "
        <> envName fun
        <> " *geng_env = (struct "
        <> envName fun
        <> " *) geng_self->env;\n"

-- EMITTING

-- | What the emitter needs that an expression does not carry: the parameters
-- of every join point in scope, so an 'XJump' knows what to assign.
data Ctx = Ctx (Map Name [(Name, Rep)]) (Map String Int)

-- | Where a value being computed has to end up.
data Dest
  = -- | @return@ it.
    Return
  | -- | Assign it to a variable that already exists.
    Slot B.Builder
  | -- | Inside a trampoline step: this is the group's answer, so record it and
    -- stop bouncing.
    Bounce

-- | Emit an expression into a destination.
--
-- A statement emitter rather than an expression builder, because C's
-- expressions cannot hold a @switch@ or a label and "Core.Low" has already put
-- every intermediate value in an 'XLet'. The @[Int]@ is the path to this node,
-- which is what makes a temporary's name unique without a counter.
emit :: Ctx -> [Int] -> Dest -> Expr -> B.Builder
emit ctx path dest expr =
  case expr of
    XLet n rep value_ rest ->
      "    "
        <> ctype rep
        <> " "
        <> local n
        <> ";\n"
        <> emit ctx (0 : path) (Slot (local n)) value_
        <> emit ctx (1 : path) dest rest
    XIf cond yes no rep ->
      let t = temp path
       in "    "
            <> ctype rep
            <> " "
            <> t
            <> ";\n    if ("
            <> value cond
            <> ") {\n"
            <> emit ctx (0 : path) (Slot t) yes
            <> "    } else {\n"
            <> emit ctx (1 : path) (Slot t) no
            <> "    }\n"
            <> put dest t
    XSwitch scrut arms fallback rep ->
      let t = temp path
       in "    "
            <> ctype rep
            <> " "
            <> t
            <> ";\n    switch ("
            <> value scrut
            <> ") {\n"
            <> mconcat
              [ "    case "
                  <> B.intDec tag
                  <> ": {\n"
                  <> emit ctx (i : path) (Slot t) arm
                  <> "        break;\n    }\n"
              | (i, (tag, arm)) <- zip [0 ..] arms
              ]
            <> ( case fallback of
                   Nothing -> "    default: geng_crash(\"incomplete match\");\n"
                   Just arm ->
                     "    default: {\n"
                       <> emit ctx (99 : path) (Slot t) arm
                       <> "        break;\n    }\n"
               )
            <> "    }\n"
            <> put dest t
    -- D80's join point, and the reason it was worth writing into Core: a
    -- label and a `goto`, with no analysis to recover it. The parameters are
    -- plain locals, so entering the join is an assignment and a jump.
    XJoin name params joinBody rest ->
      mconcat ["    " <> ctype r <> " " <> local n <> ";\n" | (n, r) <- params]
        <> emit ctx (0 : path) dest rest
        <> "    goto "
        <> joinEnd name
        <> ";\n"
        <> joinLabel name
        <> ":;\n"
        <> emit ctx (1 : path) dest joinBody
        <> joinEnd name
        <> ":;\n"
    XJump name args ->
      let Ctx joins _ = ctx
          params = Map.findWithDefault [] name joins
       in -- Through temporaries, because an argument may read a parameter the
          -- same jump is about to overwrite: `sumTo (n - 1) (acc + n)` reads
          -- `n` in both arguments and assigns it in the first.
          "    {\n"
            <> mconcat
              [ "        "
                  <> ctype r
                  <> " "
                  <> jumpTemp i
                  <> " = "
                  <> value a
                  <> ";\n"
              | (i, a, (_, r)) <- zip3 [(0 :: Int) ..] args params
              ]
            <> mconcat
              [ "        " <> local n <> " = " <> jumpTemp i <> ";\n"
              | (i, (n, _)) <- zip [(0 :: Int) ..] params
              ]
            <> "        goto "
            <> joinLabel name
            <> ";\n    }\n"
    -- D14's trampoline: not a call. Write the sibling and its arguments into
    -- the bounce and return to the loop. Through temporaries for the same
    -- reason a jump uses them -- an argument may read a slot this bounce is
    -- about to overwrite.
    XBounce name args ->
      let Ctx _ targets = ctx
          j = Map.findWithDefault 0 name targets
       in "    {\n"
            <> mconcat
              [ "        "
                  <> ctype (repOfExpr a)
                  <> " "
                  <> jumpTemp k
                  <> " = "
                  <> value a
                  <> ";\n"
              | (k, a) <- zip [(0 :: Int) ..] args
              ]
            <> mconcat
              [ "        geng_b->args.m"
                  <> B.intDec j
                  <> ".geng_a"
                  <> B.intDec k
                  <> " = "
                  <> jumpTemp k
                  <> ";\n"
              | (k, _) <- zip [(0 :: Int) ..] args
              ]
            <> "        geng_b->next = "
            <> B.intDec j
            <> ";\n        return;\n    }\n"
    XCrash message _ -> "    geng_crash(" <> cstring message <> ");\n"
    _ -> put dest (value expr)

-- | Every join point bound anywhere in a body, with its parameters.
joinsIn :: Expr -> Map Name [(Name, Rep)]
joinsIn expr =
  case expr of
    XJoin name params b rest ->
      Map.unions [Map.singleton name params, joinsIn b, joinsIn rest]
    XLet _ _ v rest -> Map.union (joinsIn v) (joinsIn rest)
    XIf c y n _ -> Map.unions [joinsIn c, joinsIn y, joinsIn n]
    XSwitch s arms fallback _ ->
      Map.unions (joinsIn s : maybe Map.empty joinsIn fallback : map (joinsIn . snd) arms)
    XCallTop _ args _ -> Map.unions (map joinsIn args)
    XCallKernel _ args _ -> Map.unions (map joinsIn args)
    XCallClosure f args _ -> Map.unions (joinsIn f : map joinsIn args)
    XMakeClosure _ args -> Map.unions (map joinsIn args)
    XMakeRecord _ args -> Map.unions (map joinsIn args)
    XMakeData _ _ args -> Map.unions (map joinsIn args)
    XField r _ _ -> joinsIn r
    XTagOf s _ -> joinsIn s
    XPayload s _ _ _ _ -> joinsIn s
    XJump _ args -> Map.unions (map joinsIn args)
    _ -> Map.empty

temp :: [Int] -> B.Builder
temp path = "geng_t" <> mconcat ["_" <> B.intDec i | i <- reverse path]

jumpTemp :: Int -> B.Builder
jumpTemp i = "geng_j" <> B.intDec i

joinLabel :: Name -> B.Builder
joinLabel name = "geng_join_" <> mangleLocal (Name.toChars name)

joinEnd :: Name -> B.Builder
joinEnd name = "geng_join_end_" <> mangleLocal (Name.toChars name)

put :: Dest -> B.Builder -> B.Builder
put dest v =
  case dest of
    Return -> "    return " <> v <> ";\n"
    Slot slot -> "    " <> slot <> " = " <> v <> ";\n"
    Bounce -> "    geng_b->next = -1;\n    geng_b->value = " <> v <> ";\n    return;\n"

-- | The expressions that really are C expressions.
value :: Expr -> B.Builder
value expr =
  case expr of
    XLit lit rep -> literal lit rep
    XVar n _ -> local n
    XCapture n _ -> "geng_env->" <> local n
    XCaf name _ -> B.stringUtf8 name <> "()"
    XEnumTag _ tag -> B.intDec tag
    -- A direct call passes NULL for the environment: this function's C
    -- signature has the parameter because every function's does.
    XCallTop name args _ ->
      B.stringUtf8 name <> "(" <> commas ("NULL" : map value args) <> ")"
    XCallKernel name args _ ->
      B.stringUtf8 name <> "(" <> commas (map value args) <> ")"
    XCallClosure f args rep ->
      -- The indirect case. "Core.Low" knows every argument's Rep at this call
      -- site, so the cast is exact rather than a guess — which is the payoff
      -- of R2 refusing a uniform boxed representation.
      let closure = parens (value f)
       in "((("
            <> fnPointer rep (map repOfExpr args)
            <> ") "
            <> closure
            <> "->code)("
            <> commas (closure : map value args)
            <> "))"
    XMakeClosure name captures ->
      "geng_mk_" <> B.stringUtf8 name <> "(" <> commas (map value captures) <> ")"
    XMakeRecord tid fields ->
      "geng_new_" <> recordName tid <> "(" <> commas (map value fields) <> ")"
    XMakeData tid tag fields ->
      "geng_new_"
        <> dataName tid
        <> "_"
        <> B.intDec tag
        <> "("
        <> commas (map value fields)
        <> ")"
    -- No TypeId here: the pointer is already typed, so `->f_x` resolves to
    -- this struct's field and no other. "Core.Low" decided the layout; C's own
    -- type system is enough to name a field in it.
    XField record f _ -> parens (value record) <> "->" <> field f
    XTagOf scrut _ -> parens (value scrut) <> "->tag"
    XPayload scrut _ tag i _ ->
      parens (value scrut) <> "->payload.c" <> B.intDec tag <> ".f" <> B.intDec i
    _ -> "0 /* not a value */"

-- | An expression's 'Rep', which the indirect-call cast needs.
--
-- Note that this is a fold over "Core.Low"'s own nodes and not a type
-- inference: every 'Expr' that can be an argument carries its 'Rep' already.
repOfExpr :: Expr -> Rep
repOfExpr expr =
  case expr of
    XLit _ r -> r
    XVar _ r -> r
    XCapture _ r -> r
    XCaf _ r -> r
    XLet _ _ _ rest -> repOfExpr rest
    XIf _ _ _ r -> r
    XSwitch _ _ _ r -> r
    XCallTop _ _ r -> r
    XCallKernel _ _ r -> r
    XCallClosure _ _ r -> r
    XMakeClosure _ _ -> RClosure
    XMakeRecord tid _ -> RRecord tid
    XField _ _ r -> r
    XMakeData tid _ _ -> RData tid
    XTagOf _ _ -> RInt
    XEnumTag tid _ -> REnum tid
    XPayload _ _ _ _ r -> r
    XJoin _ _ _ rest -> repOfExpr rest
    XJump _ _ -> RInt
    -- A trampoline jump goes in tail position and nowhere else ('bounce' puts
    -- it there), so it is emitted as a statement and never asked what it is
    -- worth. 'XJump' answers 'RInt' above for the same shape of reason and is
    -- reachable, since a join point's body ends in one.
    XBounce _ _ -> RInt
    XCrash _ r -> r

-- | A constant, printed at the representation it is used at.
--
-- The 'Rep' and not the 'Lit' decides, and the two disagree often enough that
-- it matters: Core spells every M1a integer literal @LIntLegacy@, so the @2@ in
-- @x / 2@ over @Float@ arrives here as an integer and has to print as
-- @2.0@. "Core.Low" resolved that; this only obeys.
literal :: Lit -> Rep -> B.Builder
literal lit rep =
  case (rep, lit) of
    (RFloat, LInt n) -> B.stringUtf8 (showDouble (fromIntegral n))
    (RFloat, LFloat d) -> B.stringUtf8 (showDouble d)
    (_, LFloat d) -> B.stringUtf8 (showDouble d)
    (_, LInt n) -> "INT32_C(" <> B.stringUtf8 (show n) <> ")"
    (_, LChar c) -> "INT32_C(" <> B.intDec c <> ")"
    (_, LString str) -> "geng_string_literal(" <> cstring str <> ")"

-- | A double C reads back as the same value: a hex float, which is exact.
showDouble :: Double -> String
showDouble d
  | isNaN d = "(0.0/0.0)"
  | isInfinite d = if d > 0 then "(1.0/0.0)" else "(-1.0/0.0)"
  | otherwise = Numeric.showHFloat d ""

cstring :: String -> B.Builder
cstring s = "\"" <> mconcat (map escape s) <> "\""
  where
    escape c =
      case c of
        '"' -> "\\\""
        '\\' -> "\\\\"
        '\n' -> "\\n"
        '\t' -> "\\t"
        _ -> B.stringUtf8 [c]

-- ALLOCATION

recordAlloc :: RecordLayout -> B.Builder
recordAlloc (RecordLayout tid fields) =
  "static struct "
    <> recordName tid
    <> " *geng_new_"
    <> recordName tid
    <> "("
    <> ( case [ctype r <> " " <> field f | (f, r) <- fields] of
           [] -> "void"
           ps -> commas ps
       )
    <> ") {\n    struct "
    <> recordName tid
    <> " *geng_it = geng_alloc(sizeof *geng_it);\n"
    <> mconcat ["    geng_it->" <> field f <> " = " <> field f <> ";\n" | (f, _) <- fields]
    <> "    return geng_it;\n}\n\n"

dataAlloc :: DataLayout -> B.Builder
dataAlloc layout
  | _dlEnum layout = ""
  | otherwise =
      mconcat
        [ "static struct "
            <> dataName (_dlId layout)
            <> " *geng_new_"
            <> dataName (_dlId layout)
            <> "_"
            <> B.intDec (_clTag c)
            <> "("
            <> ( case [ctype r <> " f" <> B.intDec i | (i, r) <- zip [(0 :: Int) ..] (_clFields c)] of
                   [] -> "void"
                   ps -> commas ps
               )
            <> ") {\n    struct "
            <> dataName (_dlId layout)
            <> " *geng_it = geng_alloc(sizeof *geng_it);\n    geng_it->tag = "
            <> B.intDec (_clTag c)
            <> ";\n"
            <> mconcat
              [ "    geng_it->payload.c"
                  <> B.intDec (_clTag c)
                  <> ".f"
                  <> B.intDec i
                  <> " = f"
                  <> B.intDec i
                  <> ";\n"
              | (i, _) <- zip [(0 :: Int) ..] (_clFields c)
              ]
            <> "    return geng_it;\n}\n\n"
        | c <- _dlCtors layout
        ]

-- ENTRY

-- | @main()@: compute the root and print it.
--
-- §X3 is what makes this a spike rather than a runtime. The root is a scalar
-- binding, so there is no @Program@, no @Task@, no scheduler and no Gren
-- @main@ — the C @main@ calls one accessor and formats one value.
entryPoint :: Program -> B.Builder
entryPoint prog =
  let (root, rep) = _lowRoot prog
   in "int main(void) {\n    geng_heap_init();\n    "
        <> printer rep (B.stringUtf8 root <> "()")
        <> "\n    return 0;\n}\n"

printer :: Rep -> B.Builder -> B.Builder
printer rep v =
  case rep of
    RInt -> "geng_print_int(" <> v <> ");"
    RChar -> "geng_print_int(" <> v <> ");"
    REnum _ -> "geng_print_int(" <> v <> ");"
    RFloat -> "geng_print_float(" <> v <> ");"
    RString -> "geng_print_string(" <> v <> ");"
    _ -> "geng_print_opaque();"

-- HELPERS

field :: Name -> B.Builder
field f = "f_" <> mangleLocal (Name.toChars f)

local :: Name -> B.Builder
local n = "v_" <> mangleLocal (Name.toChars n)

-- | A Gren local may hold characters C will not: the frontend generates names
-- with @$@ in them.
mangleLocal :: String -> B.Builder
mangleLocal = B.stringUtf8 . concatMap one
  where
    one c
      | c `elem` ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_" :: String) = [c]
      | otherwise = "_"

commas :: [B.Builder] -> B.Builder
commas = mconcat . List.intersperse ", "

parens :: B.Builder -> B.Builder
parens b = "(" <> b <> ")"
